### ISSUE TITLE
Not a linux console?

### ISSUE THREAD

**Issue by wozzo** [kbfirebreather/rpi-digital-photo-frame#1]
Hi,
Firstly, thanks for pointing me in the direction of fbi. All other photo frame options said feh, but that requires the gui to be running and I wanted to run something from the command line. 
I'm having a problem though running the slideshow.sh script. I've added it to /etc/rc.local just before exit 0 but when it runs I can see the following error. 

```
using "DejaVu Sans Mono-16", pixelsize=16.67 file=/usr/share/fonts/truetype/dejavu/Deja
VuSansMono.ttf                                                                         
ioctl VT_GETSTATE: Inappropriate ioctl for device (not a linux console?) 
```

(NB. I would get the same error if I attempted to run the command from an SSH session)
Do you have any idea why this would be and how to fix it? NB. I'm a windows developer so technical, but minimal knowledge of Linux.

**Comment by jn3va** [comment]
wozzo - Did you ever solve this?  I have the same issue.  I was running Debian Weezy and this worked fine previously, but recently rebuilt and upgraded to Debian Jessie and now it won;t work for me.
